services:
  redis:
    ports:
      - "127.0.0.1:6379:6379"
  api:
    ports:
      - "127.0.0.1:8000:8000"
    command: uvicorn app.main:sio_asgi_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    develop:
      watch:
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
  caddy:
    profiles: ["prod-only"]
